//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CMS.rc
//
#define ID_INDICATOR_USERNAME           1
#define ID_INDICATOR_USERTYPE           2
#define ID_INDICATOR_NAMECAP            3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_STRING_APPTITILE            101
#define IDC_LOG_TREECTRL                101
#define IDC_LOGMSG_LISTCTRL             102
#define ID_INDICATOR_DATETIME           102
#define IDC_RTUCFG_TREECTRL             103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_RTUCFG_GRIDCTRL             104
#define IDC_MAIN_TREECTRL               105
#define IDR_MAINFRAME2                  105
#define IDC_MAIN_GRIDCTRL               106
#define IDC_THREAD_GRID                 107
#define IDC_ADDSTRTU_GRID               108
#define IDC_RTU_AUTOGRID                109
#define IDC_RTU_YCQUERYGRIDCTRL         110
#define IDC_DATASHOW_GRIDCTRL           111
#define IDC_RAINALERT_GRID              112
#define IDC_ANALOGLIMIT_GRID            113
#define IDC_WQUALITY_GRID               114
#define IDC_WATERLEVEL_GRIDCTRL         115
#define IDC_WPRESS_GRIDCTRL             116
#define IDC_FLOW_GRIDCTRL               117
#define IDC_QUERYEVENT_GRIDCTRL         118
#define IDC_USERS_GRIDCRTL              119
#define IDC_LOGCFG_GRIDCTRL             120
#define IDC_DAYHIS_GRIDCTRL             121
#define IDC_PULSE_GRID                  122
#define IDC_HISDATASHOW_GRIDCTRL        123
#define IDR_MAINFRAME                   128
#define IDR_CMSTYPE                     129
#define IDD_DLG_CFGDSN                  131
#define IDI_ICON_RTUPRO                 135
#define IDD_DLG_LOGVIEW                 137
#define IDI_ICON_LOG                    139
#define IDD_DLG_SHOWLOG                 140
#define IDR_MENU_POP                    141
#define IDD_DLG_LOGQUERY                142
#define IDI_RTUCFG_OLDFRAME             143
#define IDR_MENU_RTYCFG                 144
#define IDR_MENU_LOGFRAME               145
#define IDD_DLG_ADDST                   146
#define IDD_DLG_START                   147
#define IDD_DLG_CFGCOMINFO              148
#define IDD_DLG_CFGNETINFO              149
#define IDI_ICON_RTUROOT                150
#define IDI_ICON_RTUST                  151
#define IDI_ICON_LOGFRAME               152
#define IDI_ICON_LOGINFO                153
#define IDD_DLG_ADDYC                   154
#define IDD_DLG_ADDYX                   155
#define IDD_DLG_ADDYK                   156
#define IDD_DLG_ADDZD                   157
#define IDD_DLG_CFGLOGOPT               158
#define IDB_BMP_START                   161
#define IDR_LOG_FRAME                   165
#define IDD_DLG_EXIT                    166
#define IDI_ICON_LOGITEM                169
#define IDI_RTUCFG_FRAME                170
#define IDD_DLG_DATAINDBLOG             171
#define IDI_CMS_UNCONNECT               175
#define IDI_CMS_UNKNOWN                 176
#define IDI_CMS_CONNECT                 178
#define IDI_THRD_STOP                   181
#define IDI_THRD_PAUSE                  182
#define IDI_THRD_RUN                    183
#define IDD_DLG_COMMSERVER              184
#define IDD_DLG_COMMTHREADPRO           185
#define IDR_MENU_BACKUP                 186
#define IDD_DLG_DATAAUTO                186
#define IDI_ICON_THREAD                 187
#define IDD_DLG_RTUPRO                  188
#define IDD_RTU_BAINFO                  189
#define IDD_RTU_AUTOSET                 190
#define IDD_RTU_WORKMODE                191
#define IDD_RTU_MODULE                  192
#define IDD_RTU_DATASHOW                193
#define IDD_RTU_PROSET                  194
#define IDD_RTU_ALERTMONI               195
#define IDD_RTU_WQUALITY                196
#define IDD_RTU_ALARMSTATE              197
#define IDD_RTU_CONTROLCMD              198
#define IDD_RTU_WATERVALUME             199
#define IDD_RTU_WATERLEVEL              200
#define IDD_RTU_WATERPRESS              201
#define IDD_RTU_FLOW                    202
#define IDD_RTU_RAINVALUME              203
#define IDD_RTU_QUERYEVENT              204
#define IDD_DLG_USERMN                  205
#define IDI_ICON_USERS                  207
#define IDD_DLG_USERPRO                 208
#define IDD_DLG_LOGIN                   209
#define IDD_DLG_EDITPWD                 210
#define IDD_RTU_DAYHISQUERY             211
#define IDD_DLG_LOGMSG                  212
#define IDD_RTU_PULSE                   213
#define IDD_RTU_COMMS                   214
#define IDD_RTU_HISQUERY                215
#define IDD_DLG_HYDRPRO                 219
#define IDD_RTU_PROSET_HYDR             221
#define IDD_RTU_AUTOSET_HYDR            222
#define IDD_RTU_QUERY_HYDRINFO          223
#define IDD_RTU_QUERY_WORKCONDITION     224
#define IDD_RTU_QUERY_COLLECTCTRL       225
#define IDD_RTU_QUERY_TRANSCTRL         226
#define IDD_RTU_WATERLEVEL_HYDR         227
#define IDD_RTU_RAIN_HYDR               228
#define IDD_RTU_SOIL_MOISTURE_HYDR      229
#define IDD_RTU_INSTANTANEOUS_DEPTH_GROUNDWATER_HYDR 230
#define IDD_RTU_INSTANTANEOUS_T_GROUNDWATER_HYDR 231
#define IDD_RTU_EVAPORATE_HYDR          232
#define IDD_RTU_FLOW_HYDR               233
#define IDD_RTU_QUERY_INTERFACE         234
#define IDD_RTU_WRITEUPDATE             235
#define IDD_RTU_PROSET_SYQ              236
#define IDD_DLG_SYQ_CFG1                237
#define IDD_DLG_SYQ_CFG2                239
#define IDD_DLG_SYQ_CFG3                240
#define IDD_DLG_SYQ_CALLDATA            241
#define IDD_DLG_SYQ_CALL_DATA2          242
#define IDD_DLG_SYQ_CALL_DATA1          243
#define IDD_DLG_SYQ_STATEANDWARING      244
#define IDD_DLG_SYQ_STATE               244
#define IDC_EDIT_DSN                    1000
#define IDC_EDIT_PWD                    1001
#define IDC_DTP_BEGIN                   1001
#define IDC_EDIT_UID                    1002
#define IDC_DTP_END                     1002
#define IDC_LIST1                       1003
#define IDC_BTN_SEARCH                  1004
#define IDC_LIST_YAOSU2                 1004
#define IDC_STATIC_DATETIME             1005
#define IDC_STATIC_LOGLEVEL             1006
#define IDC_STATIC_LOGTYPE              1007
#define IDC_EDIT_LOGMESSAGE             1008
#define IDC_LOG_TYPE                    1009
#define IDC_BEGIN_TIME                  1010
#define IDC_END_TIME                    1011
#define IDC_QUERY_TYPE                  1012
#define IDC_BEGIN_TEXT                  1013
#define IDC_END_TEXT                    1014
#define IDC_CMB_RROVINCE                1015
#define IDC_CMB_REGION                  1016
#define IDC_CMB_COUNTY                  1017
#define IDC_EDI_NAME                    1018
#define IDC_CMB_A3                      1019
#define IDC_EDI_A2                      1020
#define IDC_CMB_CMTYPE                  1021
#define IDC_CMB_INTERFACE               1022
#define IDC_BTN_INTERFACECFG            1023
#define IDC_CMB_INTERFACE2              1023
#define IDC_CMB_SCCJ                    1023
#define IDC_CMB_COMNO                   1024
#define IDC_CMB_APPPROVER               1024
#define IDC_CMB_BAUND                   1025
#define IDC_CMB_CMTYPE2                 1025
#define IDC_CMB_SCFACTORY               1025
#define IDC_CMB_DATABITS                1026
#define IDC_CMB_STOPBITS                1027
#define IDC_CMB_PARIRTY                 1028
#define IDC_EDIT_NETIPADDR              1029
#define IDC_EDIT_NETPROT                1030
#define IDC_EDIT_STNAME                 1031
#define IDC_EDIT_YCNAME                 1032
#define IDC_EDIT_YCCODE                 1033
#define IDC_EDIT_SCALEMAX               1034
#define IDC_EDIT_POINTBITS              1035
#define IDC_EDIT_UNIT                   1036
#define IDC_EDIT_DISPLAYBITS            1037
#define IDC_EDIT_SCALEMIN               1038
#define IDC_CMB_YCTYPE                  1039
#define IDC_EDIT_YXNAME                 1040
#define IDC_EDIT_YXCODE                 1041
#define IDC_EDIT_YKNAME                 1042
#define IDC_EDIT_YKCODE                 1043
#define IDC_EDIT_ZDNAME                 1044
#define IDC_EDIT_ZDCODE                 1045
#define IDC_EDIT_SIZEOF                 1046
#define IDC_CHECK_CMSTATUS              1046
#define IDC_CHECK_CMBUFFER              1047
#define IDC_EDIT_ORDERINITEM            1048
#define IDC_CHECK_YKRECORD              1048
#define IDC_CHECK_YCRECORD              1049
#define IDC_CHECK_YXRECORD              1050
#define IDC_CHECK_ZDRECORD              1051
#define IDC_CHECK_SYSRUN                1052
#define IDC_CHECK_OTHERLOG              1053
#define IDC_EDIT_SAVEMONTH              1054
#define IDC_LIST_DATAINDBLOG            1055
#define IDC_BUTTON1                     1057
#define IDC_THREAD_GRIDPIC              1058
#define IDC_WORKMODE_SET                1058
#define IDC_BTN_AUTOQUERY               1058
#define IDC_BTN_ANALOGLCALL             1058
#define IDC_BTN_WQUPSET                 1058
#define IDC_BTN_QUERYCZL                1058
#define IDC_BTN_BACKUP                  1058
#define IDC_BTN_MEMORY                  1058
#define IDC_BTN_WRITE                   1058
#define IDC_BTN_REFRESH                 1059
#define IDC_YCQUERY_SET                 1059
#define IDC_BTN_ANALOGOK                1059
#define IDC_BTN_WQDOWNCALL              1059
#define IDC_BTN_QUERYSYALARM            1059
#define IDC_BTN_STORAGE                 1059
#define IDC_BTN_OK                      1060
#define IDC_BTN_WQDOWNSET               1060
#define IDC_BTN_SETSYALARM              1060
#define IDC_BTN_SOLARV                  1060
#define IDC_LIST_THDLOG                 1061
#define IDC_BTN_WQDATACALL              1061
#define IDC_BTN_TEMPERATION             1061
#define IDC_STATIC_CMPRO                1062
#define IDC_BTN_QUERY_SENSORBASE        1062
#define IDC_BTN_MEMORYPTR               1062
#define IDC_EDIT_THREADINFO             1063
#define IDC_BTN_QUERY_SENSORPARA        1063
#define IDC_BTN_RAINCNT                 1063
#define IDC_PIC_CMPRO                   1064
#define IDC_BTN_QUERY_SENSORDEF         1064
#define IDC_BTN_SETUPSTATUS             1064
#define IDC_BTN_QUERY_HYDRSENDCTRL      1065
#define IDC_BTN_QUERY_HYDRTIMESPAN      1066
#define IDC_BTN_DATAAUTOSEARCH          1067
#define IDC_BTN_QUERY_GSM               1067
#define IDC_BTN_DATAAUTOSET             1068
#define IDC_BTN_DEL_GSM                 1068
#define IDC_CUSTOM1                     1069
#define IDC_BTN_SET_GSM                 1069
#define IDC_BTN_QUERY_BD                1070
#define IDC_BTN_DEL_BD                  1071
#define IDC_BTN_SET_BD                  1072
#define IDC_TAB_RTUPRO                  1073
#define IDC_BTN_QUERY_IP                1073
#define IDC_CMB_WORKMODE                1074
#define IDC_BTN_DEL_IP                  1074
#define IDC_WORKMODE_CALL               1075
#define IDC_BTN_SET_IP                  1075
#define IDC_BA_NAME                     1076
#define IDC_YCQUERY_CALL                1076
#define IDC_BTN_QUERY_PORT              1076
#define IDC_WORKMODE_LOG                1077
#define IDC_BA_PRVIN                    1077
#define IDC_BTN_QUERY_IP2               1077
#define IDC_BA_COUNTY                   1078
#define IDC_BTN_SET_PORT                1078
#define IDC_BA_REGION                   1079
#define IDC_BTN_DEL_IP2                 1079
#define IDC_BA_A2                       1080
#define IDC_BTN_SET_IP2                 1080
#define IDC_BA_CMTYPE                   1081
#define IDC_BA_INTERFACE                1082
#define IDC_BA_IN_INFO                  1083
#define IDC_BA_RTUTYPE                  1084
#define IDC_COMBO1                      1085
#define IDC_CONN_CHECK                  1086
#define IDC_COMBO_ANALOHPARA            1086
#define IDC_CMB_USERONDUTY              1086
#define IDC_CMB_DATATYPE                1086
#define IDC_CBX_SENSORPARA              1086
#define IDC_BASIC_DTCALL                1087
#define IDC_CMB_RTUSTATE                1087
#define IDC_CMB_QUERYNO                 1087
#define IDC_CBX_SENSORDEF               1087
#define IDC_COMBO2                      1088
#define IDC_CMB_RTUALARM                1088
#define IDC_CBX_HYDRSENDCTRL            1088
#define IDC_BTN_SELTHREAD               1089
#define IDC_CBX_HYDRTIMESPAN            1089
#define IDC_BA_THDINFTEXT               1090
#define IDC_CBX_SENSORDEF2              1090
#define IDC_BA_LOGTEXT                  1091
#define IDC_BASIC_DTSET                 1091
#define IDC_CBX_BD                      1091
#define IDC_BTN_AUTOSET                 1092
#define IDC_BA_RECVTIME                 1092
#define IDC_CBX_IP                      1092
#define IDC_STATIC_AUTOGRID             1093
#define IDC_CBX_PORT                    1093
#define IDC_GC_YCQUERYPARA              1094
#define IDC_CBX_IP2                     1094
#define IDC_RTU_LOGLIST                 1095
#define IDC_DATASHOW_GRIDSTATIC         1096
#define IDC_BASIC_DT                    1097
#define IDC_TAB_RTUPROSET               1098
#define IDC_EDIT_RAINCOUNT              1099
#define IDC_EDIT_ANALOGCOUNT            1100
#define IDC_BTN_RAINASET                1101
#define IDC_BTN_ANALOGLSET              1102
#define IDC_COMBO_RAINPARA              1103
#define IDC_BTN_QUERYAREAL              1103
#define IDC_STATIC_RAINPARA             1104
#define IDC_STATIC_ANALOGPRAR           1105
#define IDC_BTN_RAINACALL               1106
#define IDC_STATIC_RAINCAPTION          1107
#define IDC_STATIC_ANALOGCAPTION        1108
#define IDC_BTN_QUERYRAINREAL           1108
#define IDC_BTN_RAINOK                  1109
#define IDC_EDIT_EXALARMVALUE           1110
#define IDC_EDIT_STATEVALUE             1111
#define IDC_EDIT_ALARMVALUE             1112
#define IDC_CMB_EXALARM                 1113
#define IDC_BTN_EXALARMCALL             1114
#define IDC_CMB_WQUALITY                1115
#define IDC_BTN_ALARMCALL               1115
#define IDC_STATIC_WQUALITY             1116
#define IDC_BTN_WQUPCALL                1117
#define IDC_EDIT_PGCODE                 1118
#define IDC_BTN_PGSTART                 1119
#define IDC_BTN_PGCLOSE                 1120
#define IDC_BTN_ICENABLE                1121
#define IDC_BTN_ICDISENABLE             1122
#define IDC_BTN_ZDINPUT                 1123
#define IDC_BTN_ZDEXIT                  1124
#define IDC_BTN_CLEARHIS                1125
#define IDC_CHECK_CLEAR1                1127
#define IDC_BTN_RESET                   1128
#define IDC_CMB_PGTYPE                  1129
#define IDC_CMB_RESETCMD                1130
#define IDC_CHECK_CLEAR2                1131
#define IDC_EDIT_CZL                    1131
#define IDC_CHECK_CLEAR3                1132
#define IDC_EDIT_REMAIN                 1132
#define IDC_CHECK_CLEAR0                1133
#define IDC_EDIT_ALERTV                 1133
#define IDC_BTN_SETCZL                  1134
#define IDC_EDIT_FLOWCOUNT              1135
#define IDC_BTN_SETFLOWPARA             1136
#define IDC_BTN_SETWPRESS               1137
#define IDC_BTN_QUERYFLOWDATA           1138
#define IDC_EDIT_WATERLEVELCOUNT        1139
#define IDC_CMB_WATERLEVEL              1140
#define IDC_STATIC_WATERLEVELGRID       1141
#define IDC_BTN_QUERYWATERLEVEL         1142
#define IDC_BTN_SETWATERLEVEL           1143
#define IDC_BTN_QUERYWATERLEVELDATA     1144
#define IDC_BTN_WATERLEVELOK            1145
#define IDC_EDIT_WPRESSCOUNT            1146
#define IDC_CMB_WPRESS                  1147
#define IDC_STATIC_WPRESSGRID           1148
#define IDC_BTN_QUERYWPRESS             1149
#define IDC_BTN_QUERYWPRESSDATA         1150
#define IDC_BTN_WPRESSOK                1151
#define IDC_CMB_FLOW                    1152
#define IDC_STATIC_FLOWGRID             1153
#define IDC_BTN_FLOWOK                  1154
#define IDC_BTN_QUERYEVENT              1155
#define IDC_STATIC_QUERYEVENTGRID       1156
#define IDC_BTN_ADDUSER                 1157
#define IDC_STATIC_USERSGRID            1158
#define IDC_EDIT_USERNAME               1159
#define IDC_EDIT_USERID                 1160
#define IDC_CMB_USERTYPE                1162
#define IDC_EDIT_USERPWD                1164
#define IDC_CMB_USERS                   1165
#define IDC_EDIT_OLDPWD                 1167
#define IDC_EDIT_NEWPWD                 1168
#define IDC_EDIT_RENEWPWD               1169
#define IDC_STATIC_LOGCFGGRID           1170
#define IDC_DT_QUERY                    1171
#define IDC_CMB_ZBTYPE                  1172
#define IDC_BTN_QUERYHIS                1173
#define IDC_STATIC_DAYHISGRID           1174
#define IDC_EDIT1                       1175
#define IDC_EDIT_DATAINFO               1175
#define IDC_EDIT_DATE                   1175
#define IDC_EDIT_ADDVCODE               1175
#define IDC_LET_SENSORVAR               1175
#define IDC_LET_PSW                     1175
#define IDC_EDIT_FILEADDR               1175
#define IDC_PSW2                        1175
#define IDC_EDIT_CENTER_ADDR            1175
#define IDC_EDIT_DINGSHI_MESSAGE        1175
#define IDC_LET_MEMORY                  1176
#define IDC_EDIT_PASSWORD               1176
#define IDC_EDIT_DINGSHI_MESSAGE2       1176
#define IDC_RICHEDIT21                  1177
#define IDC_RICHEDIT_LOGMSG             1177
#define IDC_LET_STORAGE                 1177
#define IDC_EDIT_RTU_ADDR               1177
#define IDC_EDIT_RIAN_JIABAOFAZHI       1177
#define IDC_STATIC_PULSE                1178
#define IDC_LET_SOLARV                  1178
#define IDC_EDIT_WATER_JIABAOLEVEL1     1178
#define IDC_LET_TEMPERATURE             1179
#define IDC_EDIT_WATER_JIABAOLEVEL2     1179
#define IDC_STATIC_PULSECAPTION         1180
#define IDC_LET_SENSORBASE              1180
#define IDC_LET_MEMORYPTR               1180
#define IDC_EDIT_WATER_JIABAOLEVEL3     1180
#define IDC_EDIT_PULSECOUNT             1181
#define IDC_LET_SENSORPARA              1181
#define IDC_LET_RAINCNT                 1181
#define IDC_EDIT_YC_WATERLEVEL_JIZHUN1  1181
#define IDC_COMBO_PULSEPARA             1182
#define IDC_LET_SETUPSTATUS             1182
#define IDC_LET_SENSORPARA2             1182
#define IDC_EDIT_YC_WATERLEVEL_JIZHUN2  1182
#define IDC_BTN_QUERYPULSE              1183
#define IDC_LET_HYDRSENDCTRL            1183
#define IDC_LET_BD                      1183
#define IDC_EDIT_WATERLEVEL_DATA_INTERVAL 1183
#define IDC_STATIC_SCCJ                 1184
#define IDC_LET_HYDRTIMESPAN            1184
#define IDC_LET_IP                      1184
#define IDC_EDIT_LIULIANG_JIABAO_FAZHI  1184
#define IDC_STATIC_SCFC                 1185
#define IDC_LET_PORT                    1185
#define IDC_EDIT_LIUSU_JIABAO_FAZHI     1185
#define IDC_CMB_DATAINTERFACE           1186
#define IDC_LET_IP2                     1186
#define IDC_LIST_COMMS                  1187
#define IDC_CMB_ITYPE                   1187
#define IDC_DATETIMEPICKER_BEGIN        1188
#define IDC_DATETIMEPICKER_END          1189
#define IDC_HISDATASHOW_GRIDSTATIC      1191
#define IDC_COMBO_TYPE                  1192
#define IDC_EDIT_DMASSAGE               1193
#define IDC_BUTTON2                     1194
#define IDC_STATIC_ITYPE                1195
#define IDC_BTN_SET_RAINSENSORDPI       1195
#define IDC_STATIC_TNAME                1196
#define IDC_BTN_SET_SENSORBASE          1196
#define IDC_STATIC_CAPTION              1197
#define IDC_BTN_SET_SENSORPARA          1197
#define IDC_BTN_SET_SENSORDEF           1198
#define IDC_BTN_SET_HYDRSENDCTRL        1199
#define IDC_TAB_PROSET_HYDR             1200
#define IDC_BTN_SET_HYDRTIMESPAN        1200
#define IDC_CBX_TIMETYPE                1203
#define IDC_D_START                     1205
#define IDC_D_END                       1208
#define IDC_CBX_SENSORNO                1210
#define IDC_STATIC_START                1216
#define IDC_STATIC_END                  1217
#define IDC_CMB_APPPROTOTYPE            1219
#define IDC_STATIC_A                    1220
#define IDC_BTN_QUERYRAINVAR            1221
#define IDC_TIMEIVL                     1222
#define IDC_CBX_DEPTH                   1223
#define IDC_BTN_QUERYSOIL               1224
#define IDC_BTN_QUERYGWDEPTH            1225
#define IDC_BTN_QUERYGWT                1226
#define IDC_BTN_QUERYEVAPORATE          1227
#define IDC_CBX_X_HYDRSENDCTRL          1229
#define IDC_CBX_X_HYDRTIMESPAN          1230
#define IDC_LET_RAINSTARDARD            1231
#define IDC_BTN_QUERY_RAINSTARDARD      1232
#define IDC_BTN_SET_RAINSTARDARD        1233
#define IDC_LET_RAINSENSORDPI           1234
#define IDC_BTN_QUERY_RAINSENSORDPI     1235
#define IDC_CBX_SENSORBASE              1236
#define IDC_CBX_APPPROTOTYPE            1237
#define IDC_STATIC_SYQCENTER            1238
#define IDC_LET_SCSW008                 1239
#define IDC_BTN_SENSORVAR               1240
#define IDC_STATIC_SCSW008              1240
#define IDC_CBX_DEF                     1241
#define IDC_EDI_SYQCENTER               1241
#define IDC_BTN_CHECKTIME               1243
#define IDC_CBX_GSM                     1244
#define IDC_LET_GSM                     1245
#define IDC_BTN_START                   1246
#define IDC_BTN_READ                    1247
#define IDC_BTN_SEND                    1248
#define IDC_UPDATE                      1249
#define IDC_CANCLE                      1250
#define IDC_STATIC_SYQ_YCADD            1251
#define IDC_EDI_SYQADDR                 1252
#define IDC_TAB_PROSET_SYQ              1253
#define IDC_BTN_WRITE_PASSWORD          1254
#define IDC_BTN_CFG1                    1258
#define IDC_COMBO_COMMTYPE1             1259
#define IDC_COMBO_COMMTYPE2             1260
#define IDC_BTN_CFG2                    1261
#define IDC_COMBO_COMMTYPE3             1262
#define IDC_BTN_CFG3                    1264
#define IDC_COMBO_COMMTYPE4             1265
#define IDC_BTN_CFG4                    1267
#define IDC_BTN_READ1                   1268
#define IDC_BTN_READ2                   1269
#define IDC_BTN_READ3                   1270
#define IDC_BTN_READ4                   1271
#define IDC_EDIT_ADDRESS1               1273
#define IDC_EDIT_ADDRESS2               1274
#define IDC_COMBO_RAIN_FENBIANLI        1274
#define IDC_EDIT_ADDRESS3               1275
#define IDC_COMBO_WATERLEVEL_FENBIANLI  1275
#define IDC_EDIT_ADDRESS4               1276
#define IDC_EDIT_START_HOUR             1277
#define IDC_EDIT_INTERVAL               1278
#define IDC_EDIT_WATER_LEVEL_UP         1278
#define IDC_COMBO_WORKWAY               1279
#define IDC_EDIT_WATER_LEVEL_DOWN       1279
#define IDC_EDIT_WATER_PRESSURE_UP      1280
#define IDC_EDIT_WATER_PRESSURE_DOWN    1281
#define IDC_READBTN                     1282
#define IDC_WRITEBTN                    1283
#define IDC_EDIT_WATER_VALUE            1284
#define IDC_EDIT2                       1285
#define IDC_CHECKTIME_BTN               1286
#define IDC_CALLDATA_BTN1               1287
#define IDC_DATETIME_BEGIN              1288
#define IDC_EDIT3                       1288
#define IDC_DATETIME_END                1289
#define IDC_QUERY                       1290
#define IDC_COMBO_YAOSU_LIST            1291
#define IDC_CALLDATA_BTN2               1291
#define IDC_COMBO_TIME_STEP             1292
#define IDC_EDIT_NUM                    1293
#define IDC_STATIC_TXT                  1294
#define IDC_STATIC_ST                   1296
#define IDC_STATIC_ENDT                 1297
#define IDC_LIST_DATA                   1301
#define IDC_LIST_YAOSU_DATA             1303
#define IDC_LIST_YAOSU                  1304
#define IDC_BTN_ADD                     1305
#define IDC_BTN_DEL                     1306
#define IDC_BUTTON3                     1307
#define IDC_BTN_QUERY                   1307
#define IDC_LIST_DATA1                  1308
#define IDC_LIST_DATA2                  1309
#define IDC_LIST                        1309
#define ID_Menu                         32771
#define ID_32772                        32772
#define IDM_LOGF                        32773
#define IDM_LOG_SYSTEM                  32774
#define ID_32775                        32775
#define IDM_OPTIONS_CFG                 32776
#define ID_32777                        32777
#define IDM_RTUOPTIONS_CFG              32778
#define IDM_SYSOPTION                   32779
#define IDM_LOG_EXPORT                  32780
#define IDM_LOG_DELETE                  32781
#define IDM_LOG_QUERY                   32782
#define IDM_LOG_DELALL                  32783
#define ID_32784                        32784
#define ID_32785                        32785
#define IDM_LOG_DEL1MONTH               32786
#define IDM_LOG_DEL2MONTH               32787
#define ID_32788                        32788
#define IDM_LOG_DELCUSTOM               32789
#define IDM_LOG_REFRESH                 32790
#define IDM_RTUCFG_EXIT                 32791
#define ID_32792                        32792
#define ID_32793                        32793
#define ID_32794                        32794
#define ID_32795                        32795
#define ID_32796                        32796
#define IDM_RTUCFG_RTUSTADD             32797
#define IDM_RTUCFG_YXADD                32798
#define IDM_RTUCFG_YKADD                32799
#define IDM_RTUCFG_ZDADD                32800
#define IDM_RTUCFG_YCADD                32801
#define ID_32802                        32802
#define ID_32803                        32803
#define ID_LOGFRAME_EXIT                32804
#define IDM_LOGFRAME_EXIT               32805
#define ID_32806                        32806
#define ID_32807                        32807
#define ID_32808                        32808
#define ID_32809                        32809
#define ID_32810                        32810
#define ID_32811                        32811
#define ID_1_RTU32812                   32812
#define ID_4_32813                      32813
#define ID_4_32814                      32814
#define IDM_RTUCFG_DELRTUST             32815
#define IDM_RTUCFG_RTUSTPRO             32816
#define ID_YC_32817                     32817
#define ID_YC_32818                     32818
#define IDM_YC_PRO                      32819
#define IDM_YX_PRO                      32820
#define IDM_YK_PRO                      32821
#define IDM_ZD_PRO                      32822
#define IDM_YC_DEL                      32823
#define IDM_YX_DEL                      32824
#define IDM_YK_DEL                      32825
#define IDM_ZD_DEL                      32826
#define IDM_YC_SELALL                   32827
#define IDM_YX_NOSELALL                 32828
#define IDM_YX_SELALL                   32829
#define ID_YK_32830                     32830
#define IMD_YK_SELALL                   32831
#define IDM_YK_NOSELALL                 32832
#define IDM_ZD_SELALL                   32833
#define IDM_ZD_NOSELALL                 32834
#define ID_RTU_32835                    32835
#define ID_RTU_32836                    32836
#define ID_RTU_32837                    32837
#define ID_RTU_32838                    32838
#define ID_RTU_32839                    32839
#define IDM_RTU_SELALL                  32840
#define IDM_RTU_NOSELALL                32841
#define IDM_RTU_DEL                     32842
#define IDM_RTU_PRO                     32843
#define ID_RTU_32844                    32844
#define IDM_RTU_DELSEL                  32845
#define ID_ZD_32846                     32846
#define IMD_ZD_DELSEL                   32847
#define ID_YK_32848                     32848
#define IDM_YK_DELSEL                   32849
#define ID_YX_32850                     32850
#define IDM_YX_DELSEL                   32851
#define ID_YC_32852                     32852
#define IDM_YC_DELSEL                   32853
#define IDM_YC_NOSELALL                 32854
#define IDM_YK_SELALL                   32855
#define IDM_ZD_DELSEL                   32856
#define ID_32857                        32857
#define ID_32858                        32858
#define ID_32859                        32859
#define ID_32860                        32860
#define IDM_                            32861
#define IDM_RTUCFG_NONE                 32862
#define IDM_RTUCFG_HORZ                 32863
#define IDM_RTUCFG_VERT                 32864
#define IDM_RTUCFG_BOTH                 32865
#define ID_32866                        32866
#define IDM_DBOPT_CFG                   32867
#define ID_32868                        32868
#define IDM_LOGSYSOPT_CFG               32869
#define ID_32870                        32870
#define IDM_LOGOPT_CFG                  32871
#define ID_Menu32872                    32872
#define ID_0_32873                      32873
#define ID_0_32874                      32874
#define IDM_POP_SHOWFRAME               32875
#define IDM_POP_HIDEFRAME               32876
#define ID_32892                        32892
#define ID_32896                        32896
#define IDM_DATAINDB                    32897
#define ID_32898                        32898
#define ID_32899                        32899
#define IDM_COMMSERVERCFG               32900
#define ID_32901                        32901
#define IDM_MAINGRID_NONE               32902
#define IDM_MAINGRID_HORZ               32903
#define IDM_MAINGRID_VERT               32904
#define IDM_MAINGRID_BOTH               32905
#define ID_10_32906                     32906
#define IDM_OP_CLEAR                    32907
#define IDI_DATETIME_BTN                32908
#define ID_10_32909                     32909
#define IDM_OP_SAVEAS                   32910
#define ID_32911                        32911
#define IDM_USERSYSTEM                  32912
#define IDM_USERSSYSTEM                 32913
#define ID_32914                        32914
#define IDM_USER_LOGIN                  32915
#define ID_32916                        32916
#define IDM_USER_EDITPWD                32917

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         32918
#define _APS_NEXT_CONTROL_VALUE         1310
#define _APS_NEXT_SYMED_VALUE           124
#endif
#endif
